### PR TITLE
Put variable of interest first in zero in zero intercept constrasts for limma and dream

### LINKED ISSUE #698: simple contrast with blocking variables breaks with limma/dream
### Description of the bug

The "simple" contrasts depend on the model being a zero-intercept model that allows to directly reference all levels
of the variable of interest as a separate coefficient. The catch is that this only works if the variable of interest is the *first* in the design formula. Otherwise the first level is omitted, to ensure that the design matrix remains full-rank. 

However, in both the rnaseq, dream and limma modules, the variable of interest is added **last**:

https://github.com/nf-core/differentialabundance/blob/2d93e0e78dbc7d1997b4d76099d58bbb440afd3c/modules/nf-core/deseq2/differential/templates/deseq2_differential.R#L368-L371

https://github.com/nf-core/differentialabundance/blob/2d93e0e78dbc7d1997b4d76099d58bbb440afd3c/modules/nf-core/limma/differential/templates/limma_de.R#L324-L328

https://github.com/nf-core/differentialabundance/blob/2d93e0e78dbc7d1997b4d76099d58bbb440afd3c/modules/nf-core/variancepartition/dream/templates/dream.R#L241-L242

The reason why this was done is not entirely clear for me. The RNAseq module quotes [a section from the DESeq2 vignette](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#multi-factor-designs) as justification, but as far as I can tell it doesn't provide any guidance on the order of variables, except:

> With no additional arguments to results, the log2 fold change and Wald test p value will be for the last variable in the design formula, and if this is a factor, the comparison will be the last level of this variable over the reference level (see previous [note on factor levels](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#factorlevels)).

However, this is completely irrelevant to us, since we always explicitly define a contrast. In fact, the very next sentence from the vignette reads

> However, the order of the variables of the design do not matter so long as the user specifies the comparison to build a results table for, using the name or contrast arguments of results.

## Implications

For DESeq2, everything still works fine, since the contrast is defined using a `(variable, target, reference)` tuple which figures out everything in the background. However, for limma and dream, it can lead to an "object not found" error

```
Error in eval(ej, envir = levelsenv) : object 'treatmenthND6' not found
```

## Suggested solution

At least in dream and limma, when building a zero-intercept model from the `contrasts` and `blocking_vars` parameters, put the variable of interest first, directly after `~ 0 + `. 

## Repex

this is based on the minimal test dataset

### nextflow command
```bash
nextflow run nf-core/differentialabundance -r 27702e9 \
    -profile rnaseq_dream \
    -params-file src/params.yml \
    -resume
```

### params
```yml
study_name: "test_data_dream"

input: "https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/mus_musculus/rnaseq_expression/SRP254919.samplesheet.csv"
matrix: "https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/mus_musculus/rnaseq_expression/SRP254919.salmon.merged.gene_counts.top1000cov.tsv"
feature_length_matrix: "https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/mus_musculus/rnaseq_expression/SRP254919.spoofed_lengths.tsv"
contrasts: "https://raw.githubusercontent.com/nf-core/test-datasets/refs/heads/differentialabundance/testdata/SRP254919.contrasts.yaml"
gtf: "https://ftp.ensembl.org/pub/release-81/gtf/mus_musculus/Mus_musculus.GRCm38.81.gtf.gz"
gene_sets_files: "https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/mus_musculus/gene_set_analysis/mh.all.v2022.1.Mm.symbols.gmt"
decoupler_network: "https://github.com/nf-core/test-datasets/raw/differentialabundance/modules_testdata/progeny/mouse_network.tsv"

outdir: output

shinyngs_build_app: false
```

### output

```
Command output:
  Reading file SRP254919.samplesheet.sample_metadata.tsv with tsv separator
  Reading file test_data_dream.filtered.tsv with tsv separator
  ~0 + sample_number + treatment
             sample_numbersample1 sample_numbersample2 sample_numbersample3
  SRX8042381                    1                    0                    0
  SRX8042382                    0                    1                    0
  SRX8042383                    0                    0                    1
             treatmentmCherry
  SRX8042381                1
  SRX8042382                1
  SRX8042383                1
  [1] "sample_numbersample1" "sample_numbersample2" "sample_numbersample3"
  [4] "treatmentmCherry"
  Using contrast string: treatmenthND6-treatmentmCherry

Command error:
  WARNING: While bind mounting '/scratch/nextflow/work/sturmgre/1e/73fbb4ce867ce74c9966510ee28bea:/scratch/nextflow/work/sturmgre/1e/73fbb4ce867ce74c9966510ee28bea': destination is already in the mount point list
  Loading required package: ggplot2
  Loading required package: limma
  Loading required package: BiocParallel

  Attaching package: ‘variancePartition’

  The following object is masked from ‘package:limma’:

      topTable

  Error in eval(ej, envir = levelsenv) : object 'treatmenthND6' not found
  Calls: makeContrasts -> eval -> eval
  Execution halted
```

### Command used and terminal output

```console

```

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by delfiterradas**
## PR checklist

Closes https://github.com/nf-core/differentialabundance/issues/698

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Broadcast software version numbers to `topic: versions` - [See version_topics](https://nf-co.re/blog/2025/version_topics)
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

### CODE REVIEW

File: modules/nf-core/limma/differential/templates/limma_de.R [hunk 1]
```diff
@@ -313,17 +313,15 @@ if (!is.null(opt\$formula)) {
     cat("Column names after make.names():\n   ", paste(colnames(design), collapse = ", "), "\n")
 
 } else {
-    # Build the model formula with blocking variables first
-    model_vars <- c()
+    # Put the contrast variable first in zero-intercept designs so each
+    # contrast level is represented directly in the design matrix.
+    model_vars <- c(contrast_variable)
```
Comment (SPPearce) [inline modules/nf-core/limma/differential/templates/limma_de.R]: Any reason why this is not just 
```suggestion
    model_vars <- contrast_variable
```

**Comment by pinin4fjords** [comment]
I'm pretty sure I had a reason for NOT doing this. Let me try and dig to figure it out

**Review by pinin4fjords — APPROVED** [review]
I dug into the history and docs, and this change is correct. Dismissing my earlier concern.

**Background**: I originally wrote the limma module (Feb 2023) with the contrast variable *first* in the zero-intercept formula (`~ 0 + contrast_variable + blocking`), which was correct. The DESeq2 module (Oct 2022) had it last, citing the DESeq2 vignette's recommendation to put the variable of interest at the end. When formula support was added to limma in #8429 (Jun 2025), the legacy path was refactored to match DESeq2's ordering, inadvertently introducing this bug.

**Why the ordering matters**: In `~ 0 + ...` models, `model.matrix()` gives all levels of the *first* factor their own columns. Subsequent factors have their reference level absorbed. So `~ 0 + batch + treatment` drops one treatment level from the column names, which breaks `makeContrasts()`.

**Why DESeq2 is unaffected**: DESeq2 specifies contrasts via `results(dds, contrast = c(variable, target, reference))`, which resolves internally regardless of column naming. limma and dream use `makeContrasts()` which references column names directly.

**The DESeq2 vignette citation was a red herring**: The vignette's "variable of interest last" recommendation is about which coefficient `results()` returns by default. The next sentence says "the order of the variables of the design do not matter so long as the user specifies the comparison to build a results table for" - and these modules always explicitly specify contrasts.

Minor nit from @SPPearce is valid - `model_vars <- contrast_variable` is cleaner than `model_vars <- c(contrast_variable)`.
